### PR TITLE
Extract and show stats when dry running

### PR DESCRIPTION
**Pull request by twitwi**
This counts the total number of images to be downloaded (and prints it when `-D` is used).

### CODE REVIEW

**Comment by gitouche-sur-osm** [comment]
Thank you very much! Didn't put much work into the dry run. I changed the output to : 
`18307 images in 46 sequences would have been downloaded without the dry run`

**Review by chrisdebian — COMMENTED** [review]
Hi,

Good work! Looking at the usage, I wasn't sure whether the script is now able to tell you the size of the download. I guess we could manually multiply the number of images by the image size.

Thanks for doing this good work.

Chris

**Comment by twitwi** [comment]
Yes, you can surely estimate the size as you mentioned.
I had quickly tried to see if we can easily get the individual image sizes but it does seem to be that easy without almost downloading the files.

**Comment by chrisdebian** [comment]
Thank you :-)

**Pull request merged**
